version: '2'

services:

  defaultdb:
    container_name: postgresql_db
    image: postgres:latest
    env_file:
      - .env


  extract_text:
    image: ghcr.io/rodionmaulenov/textextractpdf/text_extract
    container_name: extract_text
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
    depends_on:
      - defaultdb
    command: >
      bash -c "
              ./manage.py collectstatic --noinput &&
              ./manage.py migrate &&
              gunicorn -b 0.0.0.0:8000 home_api.wsgi:application
            "

  nginx_proxy:
    container_name: nginx_proxy
    image: ghcr.io/rodionmaulenov/textextractpdf/nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 443:443
      - 80:80
    depends_on:
    - extract_text

  acme_companion:
    container_name: acme_companion
    image: ghcr.io/rodionmaulenov/textextractpdf/acme
    env_file:
      - .env
    volumes_from:
      - nginx_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    depends_on:
      - nginx_proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:


