version: '3.9'

services:

  db_postgres:
    container_name: postgresql_db
    image: postgres:latest
    env_file:
      - .env


  extract_text:
    container_name: extract_text
    build:
      context: ./work_dir
      dockerfile: Dockerfileprod
    env_file:
      - .env
    depends_on:
      - db_postgres
    command: >
      bash -c "
              ./manage.py migrate &&
              gunicorn -b 0.0.0.0:8000 home_api.wsgi:application
            "

  nginx_proxy:
    container_name: nginx_proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
    depends_on:
    - extract_text

  certbot:
    image: certbot/certbot
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
