services:

  extract_text:
    container_name: extract_text
    build:
      context: ./work_dir
      dockerfile: Dockerfileprod
      args:
        - NO_CACHE=1

    image: "${APP_IMAGE}"
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    expose:
      - '8000'
    volumes:
      - ./persistentdata/static:/code/static
    env_file:
      - .env
    command: >
      bash -c "
              ./manage.py collectstatic --noinput &&
              ./manage.py migrate &&
              gunicorn -b 0.0.0.0:8000 home_api.wsgi:application
            "

  nginx_proxy:
    container_name: nginx_proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "${NGINX_IMAGE}"
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
      - ./persistentdata/static:/code/static
    depends_on:
    - extract_text

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./persistentdata/certbot/conf:/etc/letsencrypt
      - ./persistentdata/certbot/www:/var/www/certbot
