version: '3.8'

services:
  db_postgres:
    container_name: postgresql_db
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  extract_text:
    container_name: extract_text
    volumes:
      - ./data/static:/var/www/static
      - ./data/media:/var/www/media
    build:
      context: ./work_dir
      dockerfile: Dockerfileprod
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db_postgres
    command: >
      bash -c "
              ./manage.py collectstatic --noinput &&
              ./manage.py migrate &&
              gunicorn -b 0.0.0.0:8000 home_api.wsgi:application
            "
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./data/static:/var/www/static
      - ./data/media:/var/www/media
    ports:
      - 1337:80
    depends_on:
    - extract_text



