version: '3.8'

services:
  db_postgres:
    container_name: develop_postgresql_db
    image: postgres:latest
    env_file:
      - .env.dev

  develop_extract_text:
    container_name: develop_extract_text
    build:
      context: ./work_dir
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db_postgres
    command: >
      bash -c "
              ./manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
            "
