# Generated by Django 3.2.21 on 2023-09-11 20:45

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('locus', models.JSONField(blank=True, null=True)),
                ('file_upload', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DNK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D3S1358', models.CharField(blank=True, max_length=10, null=True)),
                ('vWA', models.CharField(blank=True, max_length=10, null=True)),
                ('D16S539', models.CharField(blank=True, max_length=10, null=True)),
                ('CSF1P0', models.CharField(blank=True, max_length=10, null=True)),
                ('TPOX', models.CharField(blank=True, max_length=10, null=True)),
                ('D8S1179', models.CharField(blank=True, max_length=10, null=True)),
                ('D21S11', models.CharField(blank=True, max_length=10, null=True)),
                ('D18S51', models.CharField(blank=True, max_length=10, null=True)),
                ('Penta_E', models.CharField(blank=True, max_length=10, null=True, verbose_name='Penta E')),
                ('D2S441', models.CharField(blank=True, max_length=10, null=True)),
                ('D19S433', models.CharField(blank=True, max_length=10, null=True)),
                ('THO1', models.CharField(blank=True, max_length=10, null=True)),
                ('FGA', models.CharField(blank=True, max_length=10, null=True)),
                ('D22S1045', models.CharField(blank=True, max_length=10, null=True)),
                ('D5S818', models.CharField(blank=True, max_length=10, null=True)),
                ('D13S317', models.CharField(blank=True, max_length=10, null=True)),
                ('D7S820', models.CharField(blank=True, max_length=10, null=True)),
                ('D6S1043', models.CharField(blank=True, max_length=10, null=True)),
                ('D10S1248', models.CharField(blank=True, max_length=10, null=True)),
                ('D1S1656', models.CharField(blank=True, max_length=10, null=True)),
                ('D12S391', models.CharField(blank=True, max_length=10, null=True)),
                ('D2S1338', models.CharField(blank=True, max_length=10, null=True)),
                ('Penta_D', models.CharField(blank=True, max_length=10, null=True, verbose_name='Penta D')),
                ('child', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upload_file.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upload_file.client'),
        ),
    ]
