# Generated by Django 4.2.4 on 2023-08-09 22:08

from django.db import migrations, models
import django.db.models.deletion
import upload_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('locus', models.JSONField(blank=True, null=True)),
                ('file_upload', models.FileField(upload_to=upload_file.models.user_directory_path)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DNK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus', models.CharField(blank=True, choices=[('D3S1358', 'D3S1358'), ('vWa', 'vWa'), ('D16S539', 'D16S539'), ('CSF1P0', 'CSF1P0'), ('TPOX', 'TPOX'), ('D8S1179', 'D8S1179'), ('D21S11', 'D21S11'), ('D18S51', 'D18S51'), ('Penta E', 'Penta E'), ('D2S441', 'D2S441'), ('D19S433', 'D19S433'), ('THO1 E', 'THO1 E'), ('FGA', 'FGA'), ('D22S1045', 'D22S1045'), ('D5S818', 'D5S818'), ('D13S317', 'D13S317'), ('D7S820', 'D7S820'), ('D6S1043', 'D6S1043'), ('D10S1248', 'D10S1248'), ('D1S1656', 'D1S1656'), ('D12S391', 'D12S391'), ('D2S1338', 'D2S1338'), ('Penta', 'Penta')], max_length=10)),
                ('data', models.CharField(blank=True, max_length=10)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upload_file.child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upload_file.client'),
        ),
    ]
