# Generated by Django 4.2.4 on 2023-08-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnk',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dnk',
            name='locus',
        ),
        migrations.AddField(
            model_name='dnk',
            name='D10S1248',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D12S391',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D13S317',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D16S539',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D18S51',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D19S433',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D1S1656',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D21S11',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D22S1045',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D2S1338',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D2S441',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D3S1358',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D5S818',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D6S1043',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D7S820',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='D8S1179',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='FGA',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='Penta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='Penta_E',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Penta E'),
        ),
        migrations.AddField(
            model_name='dnk',
            name='THO1_E',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='THO1 E'),
        ),
        migrations.AddField(
            model_name='dnk',
            name='TPOX',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dnk',
            name='vWa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dnk',
            name='child',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upload_file.child'),
        ),
    ]
