# Generated by Django 4.2.4 on 2023-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_remove_dnk_data_remove_dnk_locus_dnk_d10s1248_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnk',
            name='CSF1P0',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
