# Generated by Django 3.2.21 on 2023-10-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
