# Generated by Django 4.2.4 on 2023-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_dnk_csf1p0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnk',
            name='D10S1248',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
