# Generated by Django 4.2.4 on 2023-08-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_alter_dnk_d10s1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnk',
            name='Penta',
        ),
        migrations.AddField(
            model_name='dnk',
            name='Penta_D',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Penta D'),
        ),
    ]
