# Generated by Django 3.2.22 on 2023-10-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_alter_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='file_upload',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
