# Generated by Django 4.2.4 on 2023-08-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_remove_dnk_penta_dnk_penta_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnk',
            name='THO1_E',
        ),
        migrations.AddField(
            model_name='dnk',
            name='THO1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
