# Generated by Django 3.2.22 on 2023-10-27 07:41

from django.db import migrations, models
import upload_file.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='file',
            field=models.ImageField(upload_to=upload_file.models.user_directory_path),
        ),
    ]
