# Generated by Django 4.2.4 on 2023-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_remove_dnk_tho1_e_dnk_tho1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnk',
            old_name='vWa',
            new_name='vWA',
        ),
    ]
