name: CI/CD

run-name: ${{github.actor}} is testing out Github Actions

on: [push, pull_request]

jobs:
  run_unittest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python_version: ['3.11']
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python_version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          cd ./work_dir
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up environment variables
        env:
            DB_ENGINE: ${{secrets.DB_ENGINE}}
            DB_NAME: ${{secrets.DB_NAME}}
            DB_USER: ${{secrets.DB_USER}}
            DB_PASSWORD: ${{secrets.DB_PASSWORD}}
            DB_HOST: ${{secrets.DB_HOST}}
            DB_PORT: ${{secrets.DB_PORT}}
            SECRET_KEY: ${{secrets.SECRET_KEY}}
            DEBUG: ${{secrets.DEBUG}}
            ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
        run: |
            cd ./work_dir
            echo DB_ENGINE=${DB_ENGINE} >> .env
            echo DB_NAME=${DB_NAME} >> .env
            echo DB_USER=${DB_USER}" >> .env
            echo DB_PASSWORD=${DB_PASSWORD} >> .env
            echo DB_HOST= ${DB_HOST} >> .env
            echo DB_PORT=${DB_PORT} >> .env
            echo SECRET_KEY=${SECRET_KEY} >> .env
            echo DEBUG=${DEBUG} >> .env
            echo ALLOWED_HOSTS=${ALLOWED_HOSTS} >> .env
      - name: Run tests
        run: |
          cd ./work_dir
          python3 manage.py test
          
