#name: Django Tests
#
#on:
#  push:
#    branches:
#      - main
#jobs:
#  test:
#    name: Run Tests
#    runs-on: ubuntu-latest
#
#    services:
#      postgres:
#        image: postgres:latest
#        env:
#          POSTGRES_USER: yourdbuser
#          POSTGRES_PASSWORD: yourdbpassword
#          POSTGRES_DB: yourdbname
#        ports:
#          - 5432:5432
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.11
#
#      - name: Install Dependencies
#        run: |
#          cd ./work_dir
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt  # Replace with your requirements file
#
#      - name: Set up PostgreSQL
#        run: |
#          # Perform migrations and create the database schema
#          cd ./work_dir
#          python manage.py makemigrations
#          python manage.py migrate
#
#      - name: Run Tests
#        env:
#          DEBUG: "1"
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#        run: |
#          cd ./work_dir
#          python manage.py test

name: Django Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          cd ./work_dir
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Set up PostgreSQL
        env:
          DB_NAME: ${{ secrets.TEST_DB_NAME }}
          DB_USER: ${{ secrets.TEST_DB_USER }}
          DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          DB_HOST: ${{ secrets.TEST_DB_HOST }}
          DB_PORT: ${{ secrets.TEST_DB_PORT }}
        run: |
          cd ./work_dir
          python manage.py migrate

      - name: Run Tests
        env:
          DEBUG: "1"
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          cd ./work_dir
          python manage.py test
