name: CI/CD TEXT/EXTRACT/PDF

on:
  push:
    branches:
      - main

env:
  APP_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/text_extract
  NGINX_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/nginx
  ACME_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/acme
  POSTGRES_IMAGE: ghcr.io/${{ secrets.REPOSITORY_GITHUB }}/postgres
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  DIGITAL_OCEAN_IP_ADDRESS: ${{ secrets.DIGITAL_OCEAN_IP_ADDRESS }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  NAMESPACE: ${{ secrets.NAMESPACE }}

jobs:


  deploy2:
      name: Deploy to DigitalOcean
      runs-on: ubuntu-latest
#      needs: deploy

      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ env.DIGITAL_OCEAN_IP_ADDRESS }}
            username: root
            key: ${{ env.PRIVATE_KEY }}
            script: |
              cd /home/rodion/TEXT_EXTRACT_PDF

              source .env
              echo ${{ env.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ env.NAMESPACE }} --password-stdin
              
              docker pull ghcr.io/rodionmaulenov/textextractpdf/text_extract
              docker pull ghcr.io/rodionmaulenov/textextractpdf/nginx
              docker pull ghcr.io/rodionmaulenov/textextractpdf/acme
              docker pull ghcr.io/rodionmaulenov/textextractpdf/postgres
              
              docker-compose -f docker-compose.prod.yml up -d

#docker image prune -a --filter "label=type=none"








