name: Django Tests

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: yourdbuser
          POSTGRES_PASSWORD: yourdbpassword
          POSTGRES_DB: yourdbname
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Use the appropriate Python version

      - name: Install Dependencies
        run: |
          cd ./work_dir
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Set up PostgreSQL
        run: |
          # Perform migrations and create the database schema
          cd ./work_dir
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        env:
          DEBUG: "1"
          SECRET_KEY: 'django-insecure-fy!otfu*^lbwn_%vav4rw+d$8%4afj4j5rme&$(&eh$8jh4nea'
        run: |
          cd ./work_dir
          python manage.py test