name: CI/CD

run-name: ${{github.actor}} is testing out Github Actions

on: [push, pull_request]

jobs:
  run_unittest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python_version: ['3.11']
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python_version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          cd ./work_dir
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd ./work_dir
          python3 manage.py test
          
