name: Django Tests

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_DB: djtesting
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: test-key-not-good

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          cd ./work_dir
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file

      - name: Set up PostgreSQL
        run: |
          # Perform migrations and create the database schema
          cd ./work_dir
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Tests
        env:
          DEBUG: "1"
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_HOST: ${{ env.POSTGRES_HOST }}
          DB_NAME: ${{ env.POSTGRES_DB }}
          DB_PORT: ${{ env.POSTGRES_PORT }}
        run: |
          cd ./work_dir
          python manage.py test

#name: Django Tests
#
#on:
#  push:
#    branches:
#      - main
#jobs:
#  test:
#    name: Run Tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Set up PostgreSQL environment variables
#        run: |
#          echo "POSTGRES_USER=${{ secrets.TEST_DB_USER }}" >> $GITHUB_ENV
#          echo "POSTGRES_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}" >> $GITHUB_ENV
#          echo "POSTGRES_DB=${{ secrets.TEST_DB_NAME }}" >> $GITHUB_ENV
#
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.11  # Use the appropriate Python version
#
#      - name: Install Dependencies
#        run: |
#          cd ./work_dir
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt  # Replace with your requirements file
#
#      - name: Set up PostgreSQL
#        run: |
#          # Perform migrations and create the database schema
#          cd ./work_dir
#          python manage.py makemigrations
#          python manage.py migrate
#
#      - name: Run Tests
#        env:
#          DEBUG: ${{ secrets.TEST_DEBUG }}
#          SECRET_KEY: ${{ secrets.SECRET_KEY }}
#        run: |
#          cd ./work_dir
#          python manage.py test